from datamodel_parser.migrate import Util
from datamodel_parser.migrate import Intro
from datamodel_parser.migrate import Extension
from datamodel_parser.migrate import File1
from datamodel_parser.migrate import File2
from datamodel_parser.migrate import File3
from json import dumps


class File:

    def __init__(self,logger=None,options=None,body=None):
        self.initialize(logger=logger,options=options)
        self.set_body(body=body)
        self.set_ready()
        self.set_attributes()
        self.set_intro_and_extension()
#        self.set_file()

    def initialize(self,logger=None,options=None):
        self.util = Util(logger=logger,options=options)
        self.logger  = self.util.logger  if self.util.logger  else None
        self.options = self.util.options if self.util.options else None
        self.ready   = self.util.ready   if self.util.ready   else None

    def set_body(self, body=None):
        '''
            Set the body class attribute,
            a BeautifulSoup object generated by the datamodel HTML body.
        '''
        self.body = None
        if self.ready:
            self.body = body if body else None
            if not self.body:
                self.ready = False
                self.logger.error('Unable to set_body.')

    def set_ready(self):
        '''Set error indicator.'''
        self.ready = bool(self.ready   and
                          self.util    and
                          self.logger  and
                          self.options and
                          self.body)

    def set_attributes(self):
        '''Set class attributes.'''
        if self.ready:
            self.verbose = self.options.verbose if self.options else None

    def set_intro_and_extension(self):
        '''Set file intro tags and extension tags.'''
        self.intro = None
        self.extension = None
        if self.ready:
            if self.body:
                self.intro = Intro(logger  = self.logger,
                                   options = self.options,
                                   body    = self.body)
                self.extension = Extension(logger  = self.logger,
                                           options = self.options,
                                           body    = self.body)
            else:
                self.ready = False
                self.logger.error('Unable to set_intro_and_extension. ' +
                                  'self.body: '.format(self.body))

    def set_file(self):
        ''' Set class File instance.'''
        self.file = None
        if self.ready:
            self.set_template_type()
            if self.ready:
                if   self.template_type == 1: self.set_file1()
                elif self.template_type == 2: self.set_file2()
                elif self.template_type == 3: self.set_file3()
                else:
                    self.ready = False
                    self.logger.error(
                                'Unable to set_file. ' +
                                'Unable to determine datamodel template_type')

    def set_template_type(self):
        '''Determine the datamodel template type.'''
        self.template_type = None
        if self.ready:
            all_divs = self.util.children_all_one_tag_type(node     = self.body,
                                                           tag_name = 'div')

            self.ready = self.ready and self.util.ready
            if self.ready:
                if all_divs: self.set_template_type_div()
                else:        self.set_template_type_nondiv()

    def set_template_type_div(self):
        '''Determine the datamodel template type from the first division tag.'''
        self.template_type = None
        if self.ready:
            if self.body:
                div = self.body.find_next('div')
                div_id = div['id'] if div else None
                if div_id == 'intro':
                    child_names = self.util.get_child_names(node=div)
                    self.ready = self.ready and self.util.ready
                    if self.ready and child_names:
                        type_1_children = ['h1','h4','p','div']
                        type_2_children = ['h1','dl']
                        if  set(type_1_children).issubset(child_names):
                            self.template_type = 1
                        elif set(type_2_children).issubset(child_names):
                            self.template_type = 2
                        else:
                            self.ready = False
                            self.logger.error(
                                'Unable to set_template_type_div. ' +
                                'Unexpected child names. ' +
                                'child_names: {}, '.format(child_names) +
                                'type_1_children: {}, '.format(type_1_children) +
                                'type_2_children: {}.'.format(type_2_children))
                    else:
                        self.ready = False
                        self.logger.error('Unable to set_template_type_div. ' +
                                          'child_names: {}.'.format(child_names)
                                          )
            
                else:
                    self.ready = False
                    self.logger.error('Unable to set_template_type_div. ' +
                                      "Expedted div_id='intro'." +
                                      'div_id: {}.'.format(div_id))
            else:
                self.ready = False
                self.logger.error('Unable to set_template_type_div. ' +
                                  'self.body: '.format(self.body))

    def set_template_type_nondiv(self):
        '''Determine the datamodel template type from the body tag.'''
        self.template_type = None
        if self.ready:
            if self.body:
                child_names = self.util.get_child_names(node=self.body)
                self.ready = self.ready and self.util.ready
                if self.ready and child_names:
                    type_3_children = ['h1','h3','p','ul','pre']
                    if  set(type_3_children).issubset(child_names):
                        self.template_type = 3
                    else:
                        self.ready = False
                        self.logger.error(
                            'Unable to set_template_type_nondiv. ' +
                            'Unexpected child names. ' +
                            'child_names: {}, '.format(child_names) +
                            'type_3_children: {}.'.format(type_3_children))
                else:
                    self.ready = False
                    self.logger.error('Unable to set_template_type_nondiv. ' +
                                      'child_names: {}.'.format(child_names)
                                      )
            else:
                self.ready = False
                self.logger.error('Unable to set_template_type_nondiv. ' +
                                  'self.body: '.format(self.body))

    def set_file1(self):
        '''
            Set instance of File derived class comprised of HTML div's,
            where 'dl' is not a child tag.
        '''
        if self.ready:
            if self.body:
                self.file = (File1(logger=self.logger,
                                   options=self.options,
                                   body=self.body)
                             if self.logger and self.options and self.body
                             else None)
                self.ready = bool(self.file and self.file.ready)
                if not self.ready:
                    self.logger.error(
                        'Unable to set_file1. '             +
                        'self.file: {}, '.format(self.file) +
                        'self.file.ready: {}.'.format(self.file.ready))
            else:
                self.ready = False
                self.logger.error('Unable to set_file1. ' +
                                  'divs: {},'.format(divs))

    def set_file2(self):
        '''
            Set instance of File derived class comprised of HTML div's,
            where 'dl' is not a child tag.
        '''
        if self.ready:
            if self.body:
                self.file = (File2(logger=self.logger,
                                   options=self.options,
                                   body=self.body)
                             if self.logger and self.options and self.body
                             else None)
                self.ready = bool(self.file and self.file.ready)
                if not self.ready:
                    self.logger.error(
                        'Unable to set_file2. '             +
                        'self.file: {}, '.format(self.file) +
                        'self.file.ready: {}.'.format(self.file.ready))
            else:
                self.ready = False
                self.logger.error('Unable to set_file2. ' +
                                  'divs: {}.'.format(divs))

    def set_file3(self):
        '''
            Set instance of File derived class comprised of HTML div's,
            where 'dl' is not a child tag.
        '''
        if self.ready:
            if self.body:
                self.file = (File3(logger=self.logger,
                                   options=self.options,
                                   body=self.body)
                             if self.logger and self.options and self.body
                             else None)
                self.ready = bool(self.file and self.file.ready)
                if not self.ready:
                    self.logger.error(
                        'Unable to set_file3. '             +
                        'self.file: {}, '.format(self.file) +
                        'self.file.ready: {}.'.format(self.file.ready))
            else:
                self.ready = False
                self.logger.error('Unable to set_file3. ' +
                                  'divs: {}.'.format(divs))

    def parse_file(self):
        '''Parse the given file using the determined File instance.'''
        self.intro.parse_file()
        self.extension.parse_file()
        self.ready = self.ready and self.intro.ready and self.extension.ready
        self.intro_heading_orders    = self.intro.intro_heading_orders
        self.intro_heading_levels    = self.intro.intro_heading_levels
        self.intro_heading_titles    = self.intro.intro_heading_titles
        self.intro_descriptions      = self.intro.intro_descriptions
        self.section_hdu_names       = self.intro.section_hdu_names
        self.extension_count         = self.extension.extension_count
        self.file_extension_data     = self.extension.file_extension_data
        self.file_extension_headers  = self.extension.file_extension_headers

#        print('self.intro_heading_orders: {}'.format(self.intro_heading_orders))
#        print('self.intro_heading_levels: %r' % self.intro_heading_levels)
#        print('self.intro_heading_titles: {}'.format(self.intro_heading_titles))
#        print('self.intro_descriptions: {}'.format(self.intro_descriptions))
#        print('self.section_hdu_names: {}'.format(self.section_hdu_names))
#        print('self.extension_count: {}'.format(self.extension_count))
#        print('self.file_extension_data: \n' + dumps(self.file_extension_data,indent=1))
#        print('self.file_extension_headers: {}'.format(self.file_extension_headers))
#        input('pause')

#    def parse_file(self):
#        '''Parse the given file using the determined File instance.'''
#        self.file.parse_file()
#        self.intro_heading_orders    = self.file.intro_heading_orders
#        self.intro_heading_levels    = self.file.intro_heading_levels
#        self.intro_heading_titles    = self.file.intro_heading_titles
#        self.intro_descriptions      = self.file.intro_descriptions
#        self.section_hdu_names       = self.file.section_hdu_names
#        self.extension_count         = self.file.extension_count
#        self.file_extension_data     = self.file.file_extension_data
#        self.file_extension_headers  = self.file.file_extension_headers
#
##        print('self.intro_heading_orders: {}'.format(self.intro_heading_orders))
##        print('self.intro_heading_levels: %r' % self.intro_heading_levels)
##        print('self.intro_heading_titles: {}'.format(self.intro_heading_titles))
##        print('self.intro_descriptions: {}'.format(self.intro_descriptions))
##        print('self.section_hdu_names: {}'.format(self.section_hdu_names))
##        print('self.extension_count: {}'.format(self.extension_count))
##        print('self.file_extension_data: \n' + dumps(self.file_extension_data,indent=1))
##        print('self.file_extension_headers: {}'.format(self.file_extension_headers))
##        input('pause')


