---CREATE DATABASE datamodel OWNER sdss ENCODING 'UTF8' LC_COLLATE='en_US.UTF-8' LC_CTYPE='en_US.UTF-8' TEMPLATE template0;
---CREATE SCHEMA sdss AUTHORIZATION sdss;

DROP TABLE IF EXISTS sdss.column;
DROP TABLE IF EXISTS sdss.data;
DROP TABLE IF EXISTS sdss.keyword;
DROP TABLE IF EXISTS sdss.header;
DROP TABLE IF EXISTS sdss.extension;
DROP TABLE IF EXISTS sdss.description;
DROP TABLE IF EXISTS sdss.file;
DROP TABLE IF EXISTS sdss.directory;
DROP TABLE IF EXISTS sdss.location;
DROP TABLE IF EXISTS sdss.env;
DROP TABLE IF EXISTS sdss.tree;


CREATE TABLE sdss.tree (
    id SERIAL NOT NULL PRIMARY KEY,
    edition VARCHAR(32) NOT NULL UNIQUE,
    created TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    modified TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
INSERT INTO sdss.tree (edition,created) VALUES ('dr15',NOW());

CREATE TABLE sdss.env (
    id SERIAL NOT NULL PRIMARY KEY,
    tree_id INT4 REFERENCES sdss.tree(id) NOT NULL,
    variable VARCHAR(16) NOT NULL UNIQUE,
    created TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    modified TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE sdss.location (
    id SERIAL NOT NULL PRIMARY KEY,
    env_id INT4 REFERENCES sdss.env(id) NOT NULL,
    path VARCHAR(64) NOT NULL UNIQUE,
    created TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    modified TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE sdss.directory (
    id SERIAL NOT NULL PRIMARY KEY,
    location_id INT4 REFERENCES sdss.location(id) NOT NULL,
    name VARCHAR(64) NOT NULL UNIQUE,
    depth INT2,
    created TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    modified TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE sdss.file (
    id SERIAL NOT NULL PRIMARY KEY,
    location_id INT4 REFERENCES sdss.location(id) NOT NULL,
    name VARCHAR(64) NOT NULL UNIQUE,
    extension_count INT2,
    created TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    modified TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE sdss.description (
    id SERIAL NOT NULL PRIMARY KEY,
    file_id INT4 REFERENCES sdss.file(id) NOT NULL,
    sas_path VARCHAR(128) NOT NULL UNIQUE,
    general_description VARCHAR(256) NOT NULL UNIQUE,
    naming_convention VARCHAR(128) NOT NULL UNIQUE,
    approximate_size VARCHAR(32) NOT NULL UNIQUE,
    file_type VARCHAR(32) NOT NULL UNIQUE,
    created TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    modified TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE sdss.extension (
    id SERIAL NOT NULL PRIMARY KEY,
    file_id INT4 REFERENCES sdss.file(id) NOT NULL,
    hdu_number INT2,
    created TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    modified TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE sdss.header (
    id SERIAL NOT NULL PRIMARY KEY,
    extension_id INT4 REFERENCES sdss.extension(id) NOT NULL,
    title VARCHAR(32) NOT NULL UNIQUE,
    created TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    modified TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE sdss.keyword (
    id SERIAL NOT NULL PRIMARY KEY,
    header_id INT4 REFERENCES sdss.header(id) NOT NULL,
    keyword VARCHAR(32) NOT NULL,
    value VARCHAR(80) NOT NULL,
    comment VARCHAR(80) NOT NULL,
    created TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    modified TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE sdss.data (
    id SERIAL NOT NULL PRIMARY KEY,
    extension_id INT4 REFERENCES sdss.extension(id) NOT NULL,
    is_image BOOLEAN NOT NULL DEFAULT FALSE,
    created TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    modified TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE sdss.column (
    id SERIAL NOT NULL PRIMARY KEY,
    data_id INT4 REFERENCES sdss.data(id) NOT NULL,
    name VARCHAR(32) NOT NULL,
    value VARCHAR(64) NOT NULL,
    length int2 NOT NULL,
    description VARCHAR(80),
    created TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    modified TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
